# Random seed for reproducibility
seed: 42

# Data paths
data:
  train_dir: "/rwthfs/rz/cluster/hpcwork/lect0149/train"
  test_dir: "/rwthfs/rz/cluster/hpcwork/lect0149/test"
  num_workers: 8
  prefatch_factor: 4

# Training parameters
train:
  batch_size: 128
  epochs: 5
  backbone_lr: 1e-5
  classifier_lr: 1e-4
  weight_decay: 1e-2
  mixed_precision: true

# Model configuration
model:
  type: "dinov2_vitl14_reg"
  num_classes: 275
  freeze_backbone: false
  freeze_blocks: 4

# Wandb configuration
wandb:
  project: "DinoV2-Classifier-all-data"
  group: "DeepDraw"

# Logging configuration
logging:
  log_interval: 500
  save_checkpoints: true
  checkpoint_frequency: 1
  name_appendix: 'unfreeze_05-24'

# Paths
paths:
  save_dir: 'outputs'